fix(*) lodash dependency bug in react-redux
From react-redux@4.2.0, redux@3.2.0 and redux-devtools@3.1.0, lodash@4.1 was introduced as a dependency to use the `isPlainObject` utility (and some others for the devtools).
It is breaking the build on node v5.5.0 / npm 3.3.12 - https://travis-ci.org/topheman/react-es6-redux/jobs/107848435#L1345 (and the 2 following jobs).

Error: Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in (...)/node_modules/react-redux/lib/components
Error: Module not found: Error: Cannot resolve module 'lodash/difference' in (...)/node_modules/redux-devtools/lib
Error: Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in (...)/node_modules/redux/lib

Rewinding to latest version lodash free version of react-redux (currently v4.1.2), redux (currently v3.1.7) and redux-devtools (currently v3.0.2).
You can see the previous build passing: https://travis-ci.org/topheman/react-es6-redux/jobs/105761259

A first try to install lodash v4 at the root with node 5 / npm3 was already done a few days ago, but it broke the build elsewhere (with redux-devtools): https://travis-ci.org/topheman/react-es6-redux/jobs/105759065#L2042